// flow-typed signature: cc5413e3a7a8ce3ea9c0c557864b5069
// flow-typed version: <<STUB>>/sw-precache-webpack-plugin_v^0.9.0/flow_v0.42.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'sw-precache-webpack-plugin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'sw-precache-webpack-plugin' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'sw-precache-webpack-plugin/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'sw-precache-webpack-plugin/lib/index.js' {
  declare module.exports: $Exports<'sw-precache-webpack-plugin/lib/index'>;
}
